case unlockall1: {
	Menu::Title("~w~UnlockAll");
	Menu::Subtitle("Build: 2.7.2                                 ");

	if (Menu::Option("Max Night Club Popularity")) {
		char sbuf[50];
		int stat_r;
		STATS::STAT_GET_INT($("MPPLY_LAST_MP_CHAR"), &stat_r, 1);
		snprintf(sbuf, sizeof(sbuf), "MP%i%s", stat_r, "CLUB_POPULARITY");
		STATS::STAT_SET_INT($(sbuf), 1000, 1);
	}

	if (Menu::Option("Clear Reports")) {
		if (ENTITY::DOES_ENTITY_EXIST(PLAYER::PLAYER_PED_ID()))
		{
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("BADSPORT_NUMDAYS_1ST_OFFENCE"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("BADSPORT_NUMDAYS_2ND_OFFENCE"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("BADSPORT_NUMDAYS_3RD_OFFENCE"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("BADSPORT_NUMDAYS_4TH_OFFENCE"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("BADSPORT_NUMDAYS_5TH_OFFENCE"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("BADSPORT_NUMDAYS_6TH_OFFENCE"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("BADSPORT_NUMDAYS_7TH_OFFENCE"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("BADSPORT_NUMDAYS_8TH_OFFENCE"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("BADSPORT_NUMDAYS_9TH_OFFENCE"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("BADSPORT_NUMDAYS_10TH_OFFENCE"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_1ST_OFFENCE"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_2ND_OFFENCE"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_3RD_OFFENCE"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_4TH_OFFENCE"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_5TH_OFFENCE"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_6TH_OFFENCE"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_7TH_OFFENCE"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_8TH_OFFENCE"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_9TH_OFFENCE"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_10TH_OFFENCE"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_1ST_OFFENCE"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_2ND_OFFENCE"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_3RD_OFFENCE"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_4TH_OFFENCE"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_5TH_OFFENCE"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_6TH_OFFENCE"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_7TH_OFFENCE"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_8TH_OFFENCE"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_9TH_OFFENCE"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_10TH_OFFENCE"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_1ST_OFFENCE"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_2ND_OFFENCE"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_3RD_OFFENCE"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_4TH_OFFENCE"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_5TH_OFFENCE"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_6TH_OFFENCE"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_7TH_OFFENCE"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_8TH_OFFENCE"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_9TH_OFFENCE"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_10TH_OFFENCE"), 0, true);
			STATS::STAT_SET_FLOAT(GAMEPLAY::GET_HASH_KEY("BADSPORT_RESET_MINUTES"), 1.0, true);
			STATS::STAT_SET_FLOAT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_RESET_MINUTES"), 1.0, true);
			STATS::STAT_SET_FLOAT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_RESET_MINUTES"), 1.0, true);
			STATS::STAT_SET_FLOAT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_RESET_MINUTES"), 1.0, true);
			STATS::STAT_SET_FLOAT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_OVERALL_BADSPORT"), 0, true);
			STATS::STAT_SET_BOOL(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_CHAR_IS_BADSPORT"), false, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_BECAME_BADSPORT_NUM"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BAD_SPORT_BITSET"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CHEAT_BITSET"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_REPORT_STRENGTH"), 32, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_COMMEND_STRENGTH"), 100, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_FRIENDLY"), 100, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_HELPFUL"), 100, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_GRIEFING"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_OFFENSIVE_LANGUAGE"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_OFFENSIVE_UGC"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_VC_HATE"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_GAME_EXPLOITS"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_ISPUNISHED"), 0, true);
			STATS::STAT_SET_FLOAT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_OVERALL_BADSPORT"), 0, true);
			STATS::STAT_SET_BOOL(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_CHAR_IS_BADSPORT"), false, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_BECAME_BADSPORT_NUM"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BAD_SPORT_BITSET"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CHEAT_BITSET"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_REPORT_STRENGTH"), 32, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_COMMEND_STRENGTH"), 100, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_FRIENDLY"), 100, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_HELPFUL"), 100, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_GRIEFING"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_OFFENSIVE_LANGUAGE"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_OFFENSIVE_UGC"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_VC_HATE"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_GAME_EXPLOITS"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_ISPUNISHED"), 0, true);
			STATS::STAT_SET_FLOAT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_OVERALL_BADSPORT"), 0, true);
			STATS::STAT_SET_BOOL(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_CHAR_IS_BADSPORT"), false, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_BECAME_BADSPORT_NUM"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BAD_SPORT_BITSET"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CHEAT_BITSET"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_REPORT_STRENGTH"), 32, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_COMMEND_STRENGTH"), 100, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_FRIENDLY"), 100, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_HELPFUL"), 100, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_GRIEFING"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_OFFENSIVE_LANGUAGE"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_OFFENSIVE_UGC"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_VC_HATE"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_GAME_EXPLOITS"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_ISPUNISHED"), 0, true);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("BADSPORT_NUMDAYS_1ST_OFFENCE"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("BADSPORT_NUMDAYS_2ND_OFFENCE"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("BADSPORT_NUMDAYS_3RD_OFFENCE"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("BADSPORT_NUMDAYS_4TH_OFFENCE"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("BADSPORT_NUMDAYS_5TH_OFFENCE"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("BADSPORT_NUMDAYS_6TH_OFFENCE"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("BADSPORT_NUMDAYS_7TH_OFFENCE"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("BADSPORT_NUMDAYS_8TH_OFFENCE"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("BADSPORT_NUMDAYS_9TH_OFFENCE"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("BADSPORT_NUMDAYS_10TH_OFFENCE"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_1ST_OFFENCE"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_2ND_OFFENCE"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_3RD_OFFENCE"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_4TH_OFFENCE"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_5TH_OFFENCE"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_6TH_OFFENCE"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_7TH_OFFENCE"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_8TH_OFFENCE"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_9TH_OFFENCE"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_10TH_OFFENCE"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_1ST_OFFENCE"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_2ND_OFFENCE"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_3RD_OFFENCE"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_4TH_OFFENCE"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_5TH_OFFENCE"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_6TH_OFFENCE"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_7TH_OFFENCE"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_8TH_OFFENCE"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_9TH_OFFENCE"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_10TH_OFFENCE"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_1ST_OFFENCE"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_2ND_OFFENCE"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_3RD_OFFENCE"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_4TH_OFFENCE"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_5TH_OFFENCE"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_6TH_OFFENCE"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_7TH_OFFENCE"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_8TH_OFFENCE"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_9TH_OFFENCE"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_NUMDAYS_10TH_OFFENCE"), 0, 1);
			STATS::STAT_SET_FLOAT(GAMEPLAY::GET_HASH_KEY("BADSPORT_RESET_MINUTES"), 1.0, 1);
			STATS::STAT_SET_FLOAT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_RESET_MINUTES"), 1.0, 1);
			STATS::STAT_SET_FLOAT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_RESET_MINUTES"), 1.0, 1);
			STATS::STAT_SET_FLOAT(GAMEPLAY::GET_HASH_KEY("MP2_BADSPORT_RESET_MINUTES"), 1.0, 1);
			STATS::STAT_SET_FLOAT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_OVERALL_BADSPORT"), 0, 1);
			STATS::STAT_SET_BOOL(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_CHAR_IS_BADSPORT"), false, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_BECAME_BADSPORT_NUM"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BAD_SPORT_BITSET"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CHEAT_BITSET"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_REPORT_STRENGTH"), 32, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_COMMEND_STRENGTH"), 100, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_FRIENDLY"), 100, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_HELPFUL"), 100, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_GRIEFING"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_OFFENSIVE_LANGUAGE"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_OFFENSIVE_UGC"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_VC_HATE"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_GAME_EXPLOITS"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_ISPUNISHED"), 0, 1);
			STATS::STAT_SET_FLOAT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_OVERALL_BADSPORT"), 0, 1);
			STATS::STAT_SET_BOOL(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_CHAR_IS_BADSPORT"), false, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_BECAME_BADSPORT_NUM"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BAD_SPORT_BITSET"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CHEAT_BITSET"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_REPORT_STRENGTH"), 32, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_COMMEND_STRENGTH"), 100, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_FRIENDLY"), 100, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_HELPFUL"), 100, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_GRIEFING"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_OFFENSIVE_LANGUAGE"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_OFFENSIVE_UGC"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_VC_HATE"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_GAME_EXPLOITS"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_ISPUNISHED"), 0, 1);
			STATS::STAT_SET_FLOAT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_OVERALL_BADSPORT"), 0, 1);
			STATS::STAT_SET_BOOL(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_CHAR_IS_BADSPORT"), false, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_BECAME_BADSPORT_NUM"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BAD_SPORT_BITSET"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CHEAT_BITSET"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_REPORT_STRENGTH"), 32, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_COMMEND_STRENGTH"), 100, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_FRIENDLY"), 100, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_HELPFUL"), 100, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_GRIEFING"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_OFFENSIVE_LANGUAGE"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_OFFENSIVE_UGC"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_VC_HATE"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_GAME_EXPLOITS"), 0, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_ISPUNISHED"), 0, 1);
			UI::_SET_NOTIFICATION_TEXT_ENTRY("STRING");
			UI::ADD_TEXT_COMPONENT_SUBSTRING_PLAYER_NAME("~g~Reports Removed!");
			UI::_SET_NOTIFICATION_MESSAGE_CLAN_TAG_2("CHAR_MP_STRIPCLUB_PR", "CHAR_MP_STRIPCLUB_PR", 1, 8, "~w~Saphir", "~w~Prime", 1, "UnlockAll", 9, 0);
			UI::_DRAW_NOTIFICATION(FALSE, FALSE);
		}
	}

	if (Menu::Option("Clear Badsport Stats")) {
		if (ENTITY::DOES_ENTITY_EXIST(PLAYER::PLAYER_PED_ID()))
		{
			STATS::STAT_SET_FLOAT(GAMEPLAY::GET_HASH_KEY("MPPLY_OVERALL_BADSPORT"), 0.0f, TRUE);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MPPLY_DESTROYED_PVEHICLES"), 0, TRUE);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MPPLY_BADSPORT_MESSAGE"), 0, TRUE);
			UI::_SET_NOTIFICATION_TEXT_ENTRY("STRING");
			UI::ADD_TEXT_COMPONENT_SUBSTRING_PLAYER_NAME("~g~Clear Badsport Stats Done!");
			UI::_SET_NOTIFICATION_MESSAGE_CLAN_TAG_2("CHAR_MP_STRIPCLUB_PR", "CHAR_MP_STRIPCLUB_PR", 1, 8, "~w~Saphir", "~w~Prime", 1, "UnlockAll", 9, 0);
			UI::_DRAW_NOTIFICATION(FALSE, FALSE);
		}
	}
	if (Menu::Option("Set Max Skill")) {
		if (ENTITY::DOES_ENTITY_EXIST(PLAYER::PLAYER_PED_ID()))
		{
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_SCRIPT_INCREASE_STAM"), 100, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_SCRIPT_INCREASE_STRN"), 100, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_SCRIPT_INCREASE_LUNG"), 100, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_SCRIPT_INCREASE_DRIV"), 100, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_SCRIPT_INCREASE_FLY"), 100, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_SCRIPT_INCREASE_SHO"), 100, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_SCRIPT_INCREASE_STL"), 100, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_script_increase_stam"), 100, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_script_increase_strn"), 100, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_script_increase_lung"), 100, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_script_increase_driv"), 100, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_script_increase_fly"), 100, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_script_increase_sho"), 100, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_script_increase_stl"), 100, 1);
			UI::_SET_NOTIFICATION_TEXT_ENTRY("STRING");
			UI::ADD_TEXT_COMPONENT_SUBSTRING_PLAYER_NAME("~g~Set Max Skill Done!");
			UI::_SET_NOTIFICATION_MESSAGE_CLAN_TAG_2("CHAR_MP_STRIPCLUB_PR", "CHAR_MP_STRIPCLUB_PR", 1, 8, "~w~Saphir", "~w~Prime", 1, "UnlockAll", 9, 0);
			UI::_DRAW_NOTIFICATION(FALSE, FALSE);
		}
	}
	if (Menu::Option("Unlock All Tattoos")) {
		if (ENTITY::DOES_ENTITY_EXIST(PLAYER::PLAYER_PED_ID()))
		{
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_tattoo_fm_unlocks_1"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_tattoo_fm_unlocks_2"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_tattoo_fm_unlocks_3"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_tattoo_fm_unlocks_4"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_tattoo_fm_unlocks_5"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_tattoo_fm_unlocks_6"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_tattoo_fm_unlocks_7"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_tattoo_fm_unlocks_8"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_tattoo_fm_unlocks_9"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_tattoo_fm_unlocks_10"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_tattoo_fm_unlocks_11"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_tattoo_fm_unlocks_12"), -1, 1);
			UI::_SET_NOTIFICATION_TEXT_ENTRY("STRING");
			UI::ADD_TEXT_COMPONENT_SUBSTRING_PLAYER_NAME("Unlock All Tattoos Done!");
			UI::_SET_NOTIFICATION_MESSAGE_CLAN_TAG_2("CHAR_MP_STRIPCLUB_PR", "CHAR_MP_STRIPCLUB_PR", 1, 8, "Saphir", "Prime", 1, "UnlockAll", 9, 0);
			UI::_DRAW_NOTIFICATION(FALSE, FALSE);

		}
	}
	if (Menu::Option("Add Snacks")) {
		if (ENTITY::DOES_ENTITY_EXIST(PLAYER::PLAYER_PED_ID()))
		{
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_NO_BOUGHT_YUM_SNACKS"), 99999999, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_NO_BOUGHT_HEALTH_SNACKS"), 99999999, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_NO_BOUGHT_EPIC_SNACKS"), 99999999, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CIGARETTES_BOUGHT"), 99999999, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_NUMBER_OF_ORANGE_BOUGHT"), 99999999, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_NUMBER_OF_BOURGE_BOUGHT"), 99999999, 0);
			UI::_SET_NOTIFICATION_TEXT_ENTRY("STRING");
			UI::ADD_TEXT_COMPONENT_SUBSTRING_PLAYER_NAME("Snacks Added!");
			UI::_SET_NOTIFICATION_MESSAGE_CLAN_TAG_2("CHAR_MP_STRIPCLUB_PR", "CHAR_MP_STRIPCLUB_PR", 1, 8, "Saphir", "Prime", 1, "UnlockAll", 9, 0);
			UI::_DRAW_NOTIFICATION(FALSE, FALSE);

		}
	}
	if (Menu::Option("Unlock Weapon Skins")) {
		if (ENTITY::DOES_ENTITY_EXIST(PLAYER::PLAYER_PED_ID()))
		{
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MOLOTOV _ENEMY_KILLS"), 600, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CMBTPISTOL_ENEMY_KILLS"), 600, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_PISTOL50_ENEMY_KILLS"), 600, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_APPISTOL_ENEMY_KILLS"), 600, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MICROSMG_ENEMY_KILLS"), 600, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_SMG_ENEMY_KILLS"), 600, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_ASLTSMG_ENEMY_KILLS"), 600, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_ASLTRIFLE_ENEMY_KILLS"), 600, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CRBNRIFLE_ENEMY_KILLS"), 600, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_ADVRIFLE_ENEMY_KILLS"), 600, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MG_ENEMY_KILLS"), 600, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CMBTMG_ENEMY_KILLS"), 600, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_ASLTMG_ENEMY_KILLS"), 600, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_PUMP_ENEMY_KILLS"), 600, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_SAWNOFF_ENEMY_KILLS"), 600, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BULLPUP_ENEMY_KILLS"), 600, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_ASLTSHTGN_ENEMY_KILLS"), 600, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_SNIPERRFL_ENEMY_KILLS"), 600, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_HVYSNIPER_ENEMY_KILLS"), 600, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_GRNLAUNCH_ENEMY_KILLS"), 600, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_RPG_ENEMY_KILLS"), 600, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MINIGUNS_ENEMY_KILLS"), 600, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_GRENADE_ENEMY_KILLS"), 600, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_SMKGRENADE_ENEMY_KILLS"), 600, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_STKYBMB_ENEMY_KILLS"), 600, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MOLOTOV_ENEMY_KILLS"), 600, 0);
			UI::_SET_NOTIFICATION_TEXT_ENTRY("STRING");
			UI::ADD_TEXT_COMPONENT_SUBSTRING_PLAYER_NAME("All Weapon Skins Unlocked!");
			UI::_SET_NOTIFICATION_MESSAGE_CLAN_TAG_2("CHAR_MP_STRIPCLUB_PR", "CHAR_MP_STRIPCLUB_PR", 1, 8, "Saphir", "Prime", 1, "UnlockAll", 9, 0);
			UI::_DRAW_NOTIFICATION(FALSE, FALSE);

		}
	}
	if (Menu::Option("Purchase Clothing")) {
		if (ENTITY::DOES_ENTITY_EXIST(PLAYER::PLAYER_PED_ID()))
		{
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_FEET_1"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_HAIR"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_HAIR_1"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_HAIR_2"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_HAIR_3"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_HAIR_4"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_HAIR_5"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_HAIR_6"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_HAIR_7"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_JBIB"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_JBIB_1"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_JBIB_2"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_JBIB_3"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_JBIB_4"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_JBIB_5"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_JBIB_6"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_JBIB_7"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_LEGS"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_LEGS_1"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_LEGS_2"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_LEGS_3"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_LEGS_4"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_LEGS_5"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_LEGS_6"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_LEGS_7"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_FEET"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_FEET_1"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_FEET_2"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_FEET_3"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_FEET_4"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_FEET_5"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_FEET_6"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_FEET_7"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_BERD"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_BERD_1"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_BERD_2"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_BERD_3"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_BERD_4"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_BERD_5"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_BERD_6"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_BERD_7"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_PROPS"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_PROPS_1"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_PROPS_2"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_PROPS_3"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_PROPS_4"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_PROPS_5"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_PROPS_6"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_PROPS_7"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_PROPS_8"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_PROPS_9"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_PROPS_10"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_OUTFIT"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_HAIR"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_HAIR_1"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_HAIR_2"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_HAIR_3"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_HAIR_4"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_HAIR_5"), -1, 1);;
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_HAIR_6"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_HAIR_7"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_JBIB"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_JBIB_1"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_JBIB_2"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_JBIB_3"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_JBIB_4"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_JBIB_5"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_JBIB_6"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_JBIB_7"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_LEGS"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_LEGS_1"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_LEGS_2"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_LEGS_3"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_LEGS_4"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_LEGS_5"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_LEGS_6"), -1, 1);;
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_LEGS_7"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_FEET"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_FEET_1"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_FEET_2"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_FEET_3"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_FEET_4"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_FEET_5"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_FEET_6"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_FEET_7"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_BERD"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_BERD_1"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_BERD_2"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_BERD_3"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_BERD_4"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_BERD_5"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_BERD_6"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_BERD_7"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_PROPS"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_PROPS_1"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_PROPS_2"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_PROPS_3"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_PROPS_4"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_PROPS_5"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_PROPS_6"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_PROPS_7"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_PROPS_8"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_PROPS_9"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_PROPS_10"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_OUTFIT"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_TORSO"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_SPECIAL"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_SPECIAL_1"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_SPECIAL_2"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_SPECIAL_3"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_SPECIAL_4"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_SPECIAL_5"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_SPECIAL_6"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_SPECIAL_7"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_SPECIAL2"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_SPECIAL2_1"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_DECL"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_TEETH"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_TEETH_1"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_TEETH_2"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_TORSO"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_SPECIAL"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_SPECIAL_1"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_SPECIAL_2"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_SPECIAL_3"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_SPECIAL_4"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_SPECIAL_5"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_SPECIAL_6"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_SPECIAL_7"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_SPECIAL2"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_SPECIAL2_1"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_DECL"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_TEETH"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_TEETH_1"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_ACQUIRED_TEETH_2"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_DLC_APPAREL_ACQUIRED_0"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_DLC_APPAREL_ACQUIRED_1"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_DLC_APPAREL_ACQUIRED_2"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_DLC_APPAREL_ACQUIRED_3"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_DLC_APPAREL_ACQUIRED_4"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_DLC_APPAREL_ACQUIRED_5"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_DLC_APPAREL_ACQUIRED_6"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_DLC_APPAREL_ACQUIRED_7"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_DLC_APPAREL_ACQUIRED_8"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_DLC_APPAREL_ACQUIRED_9"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_DLC_APPAREL_ACQUIRED_10"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_DLC_APPAREL_ACQUIRED_11"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_DLC_APPAREL_ACQUIRED_12"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_DLC_APPAREL_ACQUIRED_13"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_DLC_APPAREL_ACQUIRED_14"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_DLC_APPAREL_ACQUIRED_15"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_DLC_APPAREL_ACQUIRED_16"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_DLC_APPAREL_ACQUIRED_17"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_DLC_APPAREL_ACQUIRED_18"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_DLC_APPAREL_ACQUIRED_19"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_DLC_APPAREL_ACQUIRED_21"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_DLC_APPAREL_ACQUIRED_22"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_DLC_APPAREL_ACQUIRED_23"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_DLC_APPAREL_ACQUIRED_24"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_DLC_APPAREL_ACQUIRED_24"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_DLC_APPAREL_ACQUIRED_25"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_DLC_APPAREL_ACQUIRED_26"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_DLC_APPAREL_ACQUIRED_27"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_DLC_APPAREL_ACQUIRED_28"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_DLC_APPAREL_ACQUIRED_29"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_DLC_APPAREL_ACQUIRED_30"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_DLC_APPAREL_ACQUIRED_31"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_DLC_APPAREL_ACQUIRED_32"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_DLC_APPAREL_ACQUIRED_33"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_DLC_APPAREL_ACQUIRED_34"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_DLC_APPAREL_ACQUIRED_35"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_DLC_APPAREL_ACQUIRED_36"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_DLC_APPAREL_ACQUIRED_37"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_DLC_APPAREL_ACQUIRED_38"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_DLC_APPAREL_ACQUIRED_39"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_DLC_APPAREL_ACQUIRED_40"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_ADMIN_CLOTHES_GV_BS_1"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_ADMIN_CLOTHES_GV_BS_2"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_ADMIN_CLOTHES_GV_BS_3"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_ADMIN_CLOTHES_GV_BS_4"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_ADMIN_CLOTHES_GV_BS_5"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_ADMIN_CLOTHES_GV_BS_6"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_ADMIN_CLOTHES_GV_BS_7"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_ADMIN_CLOTHES_GV_BS_8"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_ADMIN_CLOTHES_GV_BS_9"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_ADMIN_CLOTHES_GV_BS_10"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_ADMIN_CLOTHES_GV_BS_11"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_ADMIN_CLOTHES_GV_BS_12"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_ADMIN_CLOTHES_GV_BS_13"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_ADMIN_CLOTHES_GV_BS_1"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_ADMIN_CLOTHES_GV_BS_10"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_ADMIN_CLOTHES_GV_BS_11"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_ADMIN_CLOTHES_GV_BS_12"), -1, 1);
			UI::_SET_NOTIFICATION_TEXT_ENTRY("STRING");
			UI::ADD_TEXT_COMPONENT_SUBSTRING_PLAYER_NAME("Clothing Unlocked!");
			UI::_SET_NOTIFICATION_MESSAGE_CLAN_TAG_2("CHAR_MP_STRIPCLUB_PR", "CHAR_MP_STRIPCLUB_PR", 1, 8, "Saphir", "Prime", 1, "UnlockAll", 9, 0);
			UI::_DRAW_NOTIFICATION(FALSE, FALSE);

		}
	}
	if (Menu::Option("Unlock LSC")) {
		if (ENTITY::DOES_ENTITY_EXIST(PLAYER::PLAYER_PED_ID()))
		{
			STATS::STAT_SET_BOOL(GAMEPLAY::GET_HASH_KEY("MP2_AWD_FMRACEWORLDRECHOLDER"), 1, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_AWD_ENEMYDRIVEBYKILLS"), 600, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_USJS_COMPLETED"), 50, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_USJS_FOUND"), 50, 0);
			STATS::STAT_SET_BOOL(GAMEPLAY::GET_HASH_KEY("MP2_AWD_FMWINALLRACEMODES"), 1, 0);
			STATS::STAT_SET_BOOL(GAMEPLAY::GET_HASH_KEY("MP2_AWD_FMWINEVERYGAMEMODE"), 1, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_DB_PLAYER_KILLS"), 1000, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_KILLS_PLAYERS"), 1000, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_AWD_FMHORDWAVESSURVIVE"), 21, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_AWD_CAR_BOMBS_ENEMY_KILLS"), 25, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_AWD_FM_TDM_MVP"), 60, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_AWD_HOLD_UP_SHOPS"), 20, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_AWD_RACES_WON"), 101, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_AWD_NO_ARMWRESTLING_WINS"), 21, 0);
			STATS::STAT_SET_BOOL(GAMEPLAY::GET_HASH_KEY("MP2_AWD_FMATTGANGHQ"), 1, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_AWD_FMBBETWIN"), 50000, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_AWD_FM_DM_WINS"), 51, 0);
			STATS::STAT_SET_BOOL(GAMEPLAY::GET_HASH_KEY("MP2_AWD_FMFULLYMODDEDCAR"), 1, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_AWD_FM_DM_TOTALKILLS"), 500, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_DM_TOTAL_DEATHS"), 412, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_TIMES_FINISH_DM_TOP_3"), 36, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_PLAYER_HEADSHOTS"), 623, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_AWD_FM_DM_WINS"), 63, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_AWD_FM_TDM_WINS"), 13, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_AWD_FM_GTA_RACES_WON"), 12, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_AWD_FM_GOLF_WON"), 2, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_AWD_FM_SHOOTRANG_TG_WON"), 2, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_AWD_FM_SHOOTRANG_RT_WON"), 2, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_AWD_FM_SHOOTRANG_CT_WON"), 2, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_AWD_FM_SHOOTRANG_GRAN_WON"), 2, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_AWD_FM_TENNIS_WON"), 2, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_TENNIS_MATCHES_WON"), 2, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_TOTAL_TDEATHMATCH_WON"), 63, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_TOTAL_RACES_WON"), 101, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_TOTAL_DEATHMATCH_LOST"), 23, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MPPLY_TOTAL_RACES_LOST"), 36, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_AWD_25_KILLS_STICKYBOMBS"), 50, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_AWD_50_KILLS_GRENADES"), 50, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_GRENADE_ENEMY_KILLS "), 50, 0);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_AWD_20_KILLS_MELEE"), 50, 0);
			UI::_SET_NOTIFICATION_TEXT_ENTRY("STRING");
			UI::ADD_TEXT_COMPONENT_SUBSTRING_PLAYER_NAME("Unlock ALC!");
			UI::_SET_NOTIFICATION_MESSAGE_CLAN_TAG_2("CHAR_MP_STRIPCLUB_PR", "CHAR_MP_STRIPCLUB_PR", 1, 8, "Saphir", "Prime", 1, "UnlockAll", 9, 0);
			UI::_DRAW_NOTIFICATION(FALSE, FALSE);
		}
	}
	if (Menu::Option("Unlock All Heist Vehicles")) {
		if (ENTITY::DOES_ENTITY_EXIST(PLAYER::PLAYER_PED_ID()))
		{
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CHAR_FM_VEHICLE_1_UNLCK"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CHAR_FM_VEHICLE_2_UNLCK"), -1, 1);
			UI::_SET_NOTIFICATION_TEXT_ENTRY("STRING");
			UI::ADD_TEXT_COMPONENT_SUBSTRING_PLAYER_NAME("Unlock All Heist Vehicles!");
			UI::_SET_NOTIFICATION_MESSAGE_CLAN_TAG_2("CHAR_MP_STRIPCLUB_PR", "CHAR_MP_STRIPCLUB_PR", 1, 8, "Saphir", "Prime", 1, "UnlockAll", 9, 0);
			UI::_DRAW_NOTIFICATION(FALSE, FALSE);

		}
	}
	if (Menu::Option("2 Billion Snacks")) {
		if (ENTITY::DOES_ENTITY_EXIST(PLAYER::PLAYER_PED_ID()))
		{
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_NO_BOUGHT_YUM_SNACKS"), 2000000000, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_NO_BOUGHT_HEALTH_SNACKS"), 2000000000, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_NO_BOUGHT_EPIC_SNACKS"), 2000000000, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_NUMBER_OF_ORANGE_BOUGHT"), 2000000000, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CIGARETTES_BOUGHT"), 2000000000, 1);
			UI::_SET_NOTIFICATION_TEXT_ENTRY("STRING");
			UI::ADD_TEXT_COMPONENT_SUBSTRING_PLAYER_NAME("2Billion Snacks!");
			UI::_SET_NOTIFICATION_MESSAGE_CLAN_TAG_2("CHAR_MP_STRIPCLUB_PR", "CHAR_MP_STRIPCLUB_PR", 1, 8, "Saphir", "Prime", 1, "UnlockAll", 9, 0);
			UI::_DRAW_NOTIFICATION(FALSE, FALSE);

		}
	}
	if (Menu::Option("2 Billion Armour")) {
		if (ENTITY::DOES_ENTITY_EXIST(PLAYER::PLAYER_PED_ID()))
		{
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MP_CHAR_ARMOUR_1_COUNT"), 2000000000, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MP_CHAR_ARMOUR_2_COUNT"), 2000000000, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MP_CHAR_ARMOUR_3_COUNT"), 2000000000, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MP_CHAR_ARMOUR_4_COUNT"), 2000000000, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_MP_CHAR_ARMOUR_5_COUNT"), 2000000000, 1);
			UI::_SET_NOTIFICATION_TEXT_ENTRY("STRING");
			UI::ADD_TEXT_COMPONENT_SUBSTRING_PLAYER_NAME("2Billion Armour!");
			UI::_SET_NOTIFICATION_MESSAGE_CLAN_TAG_2("CHAR_MP_STRIPCLUB_PR", "CHAR_MP_STRIPCLUB_PR", 1, 8, "Saphir", "Prime", 1, "UnlockAll", 9, 0);
			UI::_DRAW_NOTIFICATION(FALSE, FALSE);

		}
	}
	if (Menu::Option("2 Billion Firworks")) {
		if (ENTITY::DOES_ENTITY_EXIST(PLAYER::PLAYER_PED_ID()))
		{
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_FIREWORK_TYPE_1_WHITE"), 2000000000, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_FIREWORK_TYPE_1_RED"), 2000000000, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_FIREWORK_TYPE_1_BLUE"), 2000000000, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_FIREWORK_TYPE_2_WHITE"), 2000000000, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_FIREWORK_TYPE_2_RED"), 2000000000, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_FIREWORK_TYPE_2_BLUE"), 2000000000, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_FIREWORK_TYPE_3_WHITE"), 2000000000, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_FIREWORK_TYPE_3_RED"), 2000000000, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_FIREWORK_TYPE_3_BLUE"), 2000000000, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_FIREWORK_TYPE_4_WHITE"), 2000000000, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_FIREWORK_TYPE_4_RED"), 2000000000, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_FIREWORK_TYPE_4_BLUE"), 2000000000, 1);
			UI::_SET_NOTIFICATION_TEXT_ENTRY("STRING");
			UI::ADD_TEXT_COMPONENT_SUBSTRING_PLAYER_NAME("2Billion Fireworks!");
			UI::_SET_NOTIFICATION_MESSAGE_CLAN_TAG_2("CHAR_MP_STRIPCLUB_PR", "CHAR_MP_STRIPCLUB_PR", 1, 8, "Saphir", "Prime", 1, "UnlockAll", 9, 0);
			UI::_DRAW_NOTIFICATION(FALSE, FALSE);

		}
	}
	if (Menu::Option("Unlock All Camos and Parachutes")) {
		if (ENTITY::DOES_ENTITY_EXIST(PLAYER::PLAYER_PED_ID()))
		{
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CHAR_KIT_1_FM_UNLCK"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CHAR_KIT_2_FM_UNLCK"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CHAR_KIT_3_FM_UNLCK"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CHAR_KIT_4_FM_UNLCK"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CHAR_KIT_5_FM_UNLCK"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CHAR_KIT_6_FM_UNLCK"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CHAR_KIT_7_FM_UNLCK"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CHAR_KIT_8_FM_UNLCK"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CHAR_KIT_9_FM_UNLCK"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CHAR_KIT_10_FM_UNLCK"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CHAR_KIT_11_FM_UNLCK"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CHAR_KIT_12_FM_UNLCK"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CHAR_KIT_FM_PURCHASE"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CHAR_KIT_FM_PURCHASE2"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CHAR_KIT_FM_PURCHASE3"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CHAR_KIT_FM_PURCHASE4"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CHAR_KIT_FM_PURCHASE5"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CHAR_KIT_FM_PURCHASE6"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CHAR_KIT_FM_PURCHASE7"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CHAR_KIT_FM_PURCHASE8"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CHAR_KIT_FM_PURCHASE9"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CHAR_KIT_FM_PURCHASE10"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CHAR_KIT_FM_PURCHASE11"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CHAR_KIT_FM_PURCHASE12"), -1, 1);
			UI::_SET_NOTIFICATION_TEXT_ENTRY("STRING");
			UI::ADD_TEXT_COMPONENT_SUBSTRING_PLAYER_NAME("Unlock All Camos and Parachutes!");
			UI::_SET_NOTIFICATION_MESSAGE_CLAN_TAG_2("CHAR_MP_STRIPCLUB_PR", "CHAR_MP_STRIPCLUB_PR", 1, 8, "Saphir", "Prime", 1, "UnlockAll", 9, 0);
			UI::_DRAW_NOTIFICATION(FALSE, FALSE);

		}
	}
	if (Menu::Option("Unlock All Chrome Rims")) {
		if (ENTITY::DOES_ENTITY_EXIST(PLAYER::PLAYER_PED_ID()))
		{
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_AWD_WIN_CAPTURES"), 25, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_AWD_DROPOFF_CAP_PACKAGES"), 100, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_AWD_KILL_CARRIER_CAPTURE"), 100, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_AWD_FINISH_HEISTS"), 50, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_AWD_FINISH_HEIST_SETUP_JOB"), 50, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_AWD_WIN_LAST_TEAM_STANDINGS"), 50, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_AWD_ONLY_PLAYER_ALIVE_LTS"), 50, 1);
			UI::_SET_NOTIFICATION_TEXT_ENTRY("STRING");
			UI::ADD_TEXT_COMPONENT_SUBSTRING_PLAYER_NAME("Unlock All Chrome Rims!");
			UI::_SET_NOTIFICATION_MESSAGE_CLAN_TAG_2("CHAR_MP_STRIPCLUB_PR", "CHAR_MP_STRIPCLUB_PR", 1, 8, "Saphir", "Prime", 1, "UnlockAll", 9, 0);
			UI::_DRAW_NOTIFICATION(FALSE, FALSE);

		}
	}
	if (Menu::Option("Unlock Exclusive T-Shirts")) {
		if (ENTITY::DOES_ENTITY_EXIST(PLAYER::PLAYER_PED_ID()))
		{
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_AWD_FMHORDWAVESSURVIVE"), 10, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_AWD_FMPICKUPDLCCRATE1ST"), 1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_AWD_WIN_CAPTURE_DONT_DYING"), 25, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_AWD_DO_HEIST_AS_MEMBER"), 25, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_AWD_PICKUP_CAP_PACKAGES"), 100, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_AWD_FINISH_HEIST_NO_DAMAGE"), 1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_AWD_WIN_GOLD_MEDAL_HEISTS"), 25, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_AWD_KILL_TEAM_YOURSELF_LTS"), 25, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_AWD_KILL_PSYCHOPATHS"), 100, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_AWD_DO_HEIST_AS_THE_LEADER"), 25, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_AWD_STORE_20_CAR_IN_GARAGES"), 1, 1);
			UI::_SET_NOTIFICATION_TEXT_ENTRY("STRING");
			UI::ADD_TEXT_COMPONENT_SUBSTRING_PLAYER_NAME("Unlock Exclusive T-Shirts!");
			UI::_SET_NOTIFICATION_MESSAGE_CLAN_TAG_2("CHAR_MP_STRIPCLUB_PR", "CHAR_MP_STRIPCLUB_PR", 1, 8, "Saphir", "Prime", 1, "UnlockAll", 9, 0);
			UI::_DRAW_NOTIFICATION(FALSE, FALSE);

		}
	}
	if (Menu::Option("Unlock All Vehicle Mods (LSC)")) {
		if (ENTITY::DOES_ENTITY_EXIST(PLAYER::PLAYER_PED_ID()))
		{
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CHAR_FM_CARMOD_1_UNLCK"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CHAR_FM_CARMOD_2_UNLCK"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CHAR_FM_CARMOD_3_UNLCK"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CHAR_FM_CARMOD_4_UNLCK"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CHAR_FM_CARMOD_5_UNLCK"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CHAR_FM_CARMOD_6_UNLCK"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CHAR_FM_CARMOD_7_UNLCK"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_AWD_FMRALLYWONDRIVE"), 1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_AWD_FMRALLYWONNAV"), 1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_AWD_FMWINSEARACE"), 1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_AWD_FMWINAIRRACE"), 1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_NUMBER_TURBO_STARTS_IN_RACE"), 50, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_USJS_COMPLETED"), 50, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_AWD_FM_RACES_FASTEST_LAP"), 50, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_NUMBER_SLIPSTREAMS_IN_RACE"), 100, 1);
			UI::_SET_NOTIFICATION_TEXT_ENTRY("STRING");
			UI::ADD_TEXT_COMPONENT_SUBSTRING_PLAYER_NAME("Unlock All Vehicle Mods (LSC)!");
			UI::_SET_NOTIFICATION_MESSAGE_CLAN_TAG_2("CHAR_MP_STRIPCLUB_PR", "CHAR_MP_STRIPCLUB_PR", 1, 8, "Saphir", "Prime", 1, "UnlockAll", 9, 0);
			UI::_DRAW_NOTIFICATION(FALSE, FALSE);


		}
	}
	if (Menu::Option("Redesign Character Prompt")) {
		if (ENTITY::DOES_ENTITY_EXIST(PLAYER::PLAYER_PED_ID()))
		{
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_FM_CHANGECHAR_ASKED"), 0, 1);
			UI::_SET_NOTIFICATION_TEXT_ENTRY("STRING");
			UI::ADD_TEXT_COMPONENT_SUBSTRING_PLAYER_NAME("Redesign Character Prompt!");
			UI::_SET_NOTIFICATION_MESSAGE_CLAN_TAG_2("CHAR_MP_STRIPCLUB_PR", "CHAR_MP_STRIPCLUB_PR", 1, 8, "Saphir", "Prime", 1, "UnlockAll", 9, 0);
			UI::_DRAW_NOTIFICATION(FALSE, FALSE);

		}
	}
	if (Menu::Option("Skip Tutorial")) {
		if (ENTITY::DOES_ENTITY_EXIST(PLAYER::PLAYER_PED_ID()))
		{
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_NO_MORE_TUTORIALS"), 1, 1);
			UI::_SET_NOTIFICATION_TEXT_ENTRY("STRING");
			UI::ADD_TEXT_COMPONENT_SUBSTRING_PLAYER_NAME("Skip Tutorial!");
			UI::_SET_NOTIFICATION_MESSAGE_CLAN_TAG_2("CHAR_MP_STRIPCLUB_PR", "CHAR_MP_STRIPCLUB_PR", 1, 8, "Saphir", "Prime", 1, "UnlockAll", 9, 0);
			UI::_DRAW_NOTIFICATION(FALSE, FALSE);

		}
	}
	if (Menu::Option("Unlock All Heist' Trophies")) {
		if (ENTITY::DOES_ENTITY_EXIST(PLAYER::PLAYER_PED_ID()))
		{
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MPPLY_HEIST_ACH_TRACKER"), -1, 1);
			UI::_SET_NOTIFICATION_TEXT_ENTRY("STRING");
			UI::ADD_TEXT_COMPONENT_SUBSTRING_PLAYER_NAME("Unlock All Heist' Trophies!");
			UI::_SET_NOTIFICATION_MESSAGE_CLAN_TAG_2("CHAR_MP_STRIPCLUB_PR", "CHAR_MP_STRIPCLUB_PR", 1, 8, "Saphir", "Prime", 1, "UnlockAll", 9, 0);
			UI::_DRAW_NOTIFICATION(FALSE, FALSE);

		}
	}
	if (Menu::Option("Unlock All Hairstyles")) {
		if (ENTITY::DOES_ENTITY_EXIST(PLAYER::PLAYER_PED_ID()))
		{
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_HAIR"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_HAIR_1"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_HAIR_2"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_HAIR_3"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_HAIR_4"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_HAIR_5"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_HAIR_6"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CLTHS_AVAILABLE_HAIR_7"), -1, 1);
			UI::_SET_NOTIFICATION_TEXT_ENTRY("STRING");
			UI::ADD_TEXT_COMPONENT_SUBSTRING_PLAYER_NAME("Unlock All Hairstyles!");
			UI::_SET_NOTIFICATION_MESSAGE_CLAN_TAG_2("CHAR_MP_STRIPCLUB_PR", "CHAR_MP_STRIPCLUB_PR", 1, 8, "Saphir", "Prime", 1, "UnlockAll", 9, 0);
			UI::_DRAW_NOTIFICATION(FALSE, FALSE);

		}
	}
	if (Menu::Option("Purchase All Weapons")) {
		if (ENTITY::DOES_ENTITY_EXIST(PLAYER::PLAYER_PED_ID()))
		{
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_ADMIN_WEAPON_GV_BS_1"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_ADMIN_WEAPON_GV_BS_2"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_ADMIN_WEAPON_GV_BS_3"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_BOTTLE_IN_POSSESSION"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CHAR_FM_WEAP_UNLOCKED"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CHAR_FM_WEAP_UNLOCKED2"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CHAR_WEAP_FM_PURCHASE"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CHAR_WEAP_FM_PURCHASE2"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CHAR_FM_WEAP_ADDON_1_UNLCK"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CHAR_FM_WEAP_ADDON_2_UNLCK"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CHAR_FM_WEAP_ADDON_3_UNLCK"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CHAR_FM_WEAP_ADDON_4_UNLCK"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_CHAR_FM_WEAP_ADDON_5_UNLCK"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_WEAP_FM_ADDON_PURCH"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_WEAP_FM_ADDON_PURCH2"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_WEAP_FM_ADDON_PURCH3"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_WEAP_FM_ADDON_PURCH4"), -1, 1);
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MP2_WEAP_FM_ADDON_PURCH5"), -1, 1);
			UI::_SET_NOTIFICATION_TEXT_ENTRY("STRING");
			UI::ADD_TEXT_COMPONENT_SUBSTRING_PLAYER_NAME("Purchase All Weapons!");
			UI::_SET_NOTIFICATION_MESSAGE_CLAN_TAG_2("CHAR_MP_STRIPCLUB_PR", "CHAR_MP_STRIPCLUB_PR", 1, 8, "Saphir", "Prime", 1, "UnlockAll", 9, 0);
			UI::_DRAW_NOTIFICATION(FALSE, FALSE);

		}
	}
	if (Menu::Option("Enable Roosevelt in Phone")) {
		if (ENTITY::DOES_ENTITY_EXIST(PLAYER::PLAYER_PED_ID()))
		{
			STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MPPLY_ICLE_ID_ADMIN_WEB"), 117401876, 1);
			UI::_SET_NOTIFICATION_TEXT_ENTRY("STRING");
			UI::ADD_TEXT_COMPONENT_SUBSTRING_PLAYER_NAME("Enable Roosevelt in Phone!");
			UI::_SET_NOTIFICATION_MESSAGE_CLAN_TAG_2("CHAR_MP_STRIPCLUB_PR", "CHAR_MP_STRIPCLUB_PR", 1, 8, "Saphir", "Prime", 1, "UnlockAll", 9, 0);
			UI::_DRAW_NOTIFICATION(FALSE, FALSE);

		}
	}
}
				 break;